import React, { useState } from 'react';
import Footer from './Footer';
import Header from './Header';
import ProductList from './ProductList';
import Cart from './Cart';
import product from '../data/products';


const Productpage = () => {
    return (
        <div className="product-page">
            <Header />
            <table>
                <tbody>
                    <tr>
                        <td><ProductList /></td>
                        <td style={{ verticalAlign: 'top' }}><Cart /></td>
                    </tr>
                </tbody>
            </table>
            <Footer />
        </div>
    );
};

// changed code slightly from pdf because I got an error that said this:
// validateDOMNesting(...): <tr> cannot appear as a child of <table>. 
// Add a <tbody>, <thead> or <tfoot> to your code to match the DOM tree 
// generated by the browser

export default Productpage;

